In [35]:
import numpy as np
import scipy.linalg

### 1

In [8]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])

np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

### 2

In [15]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])

np.linalg.lstsq(A, B, rcond=None)[0]

array([ 1.13919353, -0.90498444, -0.9009803 ])

### 3

In [21]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([12, 2, 1])

print(np.linalg.matrix_rank(A))

C = np.hstack((A, B[:, np.newaxis]))

print(np.linalg.matrix_rank(C))

2
3


In [22]:
# Система не имеет решений

In [31]:
B[1] = 15
B[2] = 18

C = np.hstack((A, B[:, np.newaxis]))
print(np.linalg.matrix_rank(C))

2


In [32]:
# Система имеет бесконечное множество решений

### 4

In [36]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])

scipy.linalg.lu(A)

(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
 array([[ 1.  ,  0.  ,  0.  ],
        [ 0.25,  1.  ,  0.  ],
        [ 0.5 , -0.4 ,  1.  ]]),
 array([[  4.  ,  28.  ,  73.  ],
        [  0.  ,  -5.  , -15.25],
        [  0.  ,   0.  , -21.6 ]]))

### 5

In [37]:
def Q(x, y, z):
    return x**2 + y**2 + z**2

In [52]:
A = np.array([[1, 2, -1], [8, -5, 2]])
B = np.array([1, 12])

Y = np.linspace(-1000, 1000, num=1000000)
X = 0.1 * Y + 1.4
Z = X + 2 * Y - 1

argmin = Q(X, Y, Z).argmin()
print(X[argmin], Y[argmin], Z[argmin])

1.3818999818999826 -0.18100018100017223 0.019899619899638177


In [48]:
np.linalg.lstsq(A, B)

C:\Users\Алексей\AppData\Local\Temp\ipykernel_10384\1844739126.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A, B)


(array([ 1.38191882, -0.18081181,  0.0202952 ]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

### 6

In [60]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([2, 5, 11])

Q, R = np.linalg.qr(A)

np.dot(Q.T, B)[:2]
np.append(np.linalg.solve(R[:2, :2], np.dot(Q.T, B)[:2]), 0)

array([1.50000000e+00, 3.92767275e-15, 0.00000000e+00])